version: "3.8"

networks:
  rabbitmq-quarkus-network:
    name: rabbitmq-quarkus
    driver: bridge

volumes:
    rabbitmq_data:

services:
  rabbit:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'
    networks:
      - rabbitmq-quarkus-network

  greeting-producer:
    image: rabbitmq-quarkus/greeting-producer:1.0-${QUARKUS_MODE:-jvm}
    build:
      context: greeting-producer
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
    ports:
      - "8080:8080"
    networks:
      - rabbitmq-quarkus-network

  greeting-processor:
    image: rabbitmq-quarkus/greeting-processor:1.0-${QUARKUS_MODE:-jvm}
    build:
      context: greeting-processor
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
    networks:
      - rabbitmq-quarkus-network

